# -*- mode: ruby -*-
# vi: set ft=ruby :


# VARIABLES
BOX_IMAGE = "debian/bookworm64"
PROVIDER = "virtualbox"
NUM_CPUS = 2
MEMORIA_RAM = 2048
NOM_MAQUINA = "pj9f4a87-grup3"
HOSTNAME = "pj9f4a87-grup3.fjeclot.net"
CARPETA_MAQ_FIS1 = "../app1"
CARPETA_MAQ_FIS2 = "../app2"
CARPETA_MAQ_VIR1 = "/home/vagrant/aplicacions/app1"
CARPETA_MAQ_VIR2 = "/home/vagrant/aplicacions/app2"
PORT_VIR1 = 80
PORT_FIS1 = 8000
PORT_VIR2 = 443
PORT_FIS2 = 8443
PROT = "tcp" 


# CONFIGURACIÓ DE LA MÀQUINA

Vagrant.configure("2") do |config|
	
	# BOX
	config.vm.box = BOX_IMAGE
  
	# CONFIGURACIÓ ESPECÍFICA DEL PROVIDER
	config.vm.provider PROVIDER do |provider|
		provider.name = NOM_MAQUINA
		provider.memory = MEMORIA_RAM
		provider.cpus = NUM_CPUS
		provider.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
	end

	# CONFIGURACIÓ GENERAL
	config.vm.hostname = HOSTNAME	
	config.vm.synced_folder CARPETA_MAQ_FIS1,CARPETA_MAQ_VIR1
  config.vm.synced_folder CARPETA_MAQ_FIS2,CARPETA_MAQ_VIR2
	config.vm.network "public_network"	
	#config.vm.network "forwarded_port", guest: PORT_VIR1, host: PORT_FIS1, protocol: PROT
	#config.vm.network "forwarded_port", guest: PORT_VIR2, host: PORT_FIS2, protocol: PROT
  

	# PROGRAMARI A INSTAL·LAR I ORDRES A EXECUTAR DURANT LA CREACIÓ DE LA MÀQUINA (PROVISION)
	config.vm.provision "shell", inline: <<-SHELL
		#
		# Actualització de la llista de programari. Instal·lació del programari general
		#
		sudo apt-get -y update
		sudo apt-get -y install net-tools whois aptitude git zip unzip
		#
		# Ordres d'instal·lació de Docker. Permís a l'usuari vagrant per utiitzar Docker
		#
		sudo apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common
		curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
		sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
		sudo apt-get update -y
		sudo sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose
		sudo chown -R vagrant:vagrant /home/vagrant/pj9f4a86
		sudo gpasswd -a vagrant docker		
	SHELL
  
end
